/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2023-03-12 17:14:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import comp0004.model.element.ElementList;
import comp0004.model.element.Element;
import comp0004.model.element.thing.Thing;

public final class itemListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("comp0004.model.element.thing.Thing");
    _jspx_imports_classes.add("comp0004.model.element.ElementList");
    _jspx_imports_classes.add("comp0004.model.element.Element");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <title>List webapp</title>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .themed-grid-col {\r\n");
      out.write("            padding-top: .75rem;\r\n");
      out.write("            padding-bottom: .75rem;\r\n");
      out.write("            background-color: rgba(86, 61, 124, .15);\r\n");
      out.write("            border: 1px solid rgba(86, 61, 124, .2);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/renameLabel.jsp", out, false);
      out.write("\r\n");
      out.write("        ");

            ElementList elementList = (ElementList) request.getAttribute("list");
        
      out.write("\r\n");
      out.write("        <div class=\"container border shadow\">\r\n");
      out.write("\r\n");
      out.write("            <h2 class=\"text-center\">Text</h2>\r\n");
      out.write("            ");
 int id = 0;
                for (Element thing : elementList.getElementList()) {
                    if (thing.getLabel().equals("text")) {
                        String text = ((Thing) thing).getContent();
                        text = text.replaceAll("\n", "<br>");
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div id=\"text_edit_");
      out.print(id);
      out.write("\" contenteditable=\"false\" style=\"\">");
      out.print(text);
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <button id=\"button_edit_");
      out.print(id);
      out.write("\" onclick=\"onClickEdit(");
      out.print(id);
      out.write(")\">Edit text</button>\r\n");
      out.write("            <button type=\"submit\" form=\"form_delete_");
      out.print(id);
      out.write("\" id=\"button_delete_");
      out.print(id);
      out.write("\">Delete</button>\r\n");
      out.write("            <button type=\"submit\" form=\"form_edit_");
      out.print(id);
      out.write("\" id=\"button_yes_");
      out.print(id);
      out.write("\" style=\"display: none\"\r\n");
      out.write("                    onclick=\"onClickYes(");
      out.print(id);
      out.write(")\">Accept changes\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"button_no_");
      out.print(id);
      out.write("\" style=\"display: none\" onclick=\"onClickNo(");
      out.print(id);
      out.write(")\">Cancel changes</button>\r\n");
      out.write("\r\n");
      out.write("            <form id=\"form_edit_");
      out.print(id);
      out.write("\" action=\"editThing.html\" method=\"POST\">\r\n");
      out.write("                <input type=\"hidden\" name=\"list\" value=\"");
      out.print(elementList.getID());
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" name=\"thing\" value=\"");
      out.print(thing.getID());
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" id=\"thing_content_");
      out.print(id);
      out.write("\" name=\"thing_content\" value=\"\">\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <form id=\"form_delete_");
      out.print(id);
      out.write("\" action=\"deleteThing.html\" method=\"POST\">\r\n");
      out.write("                <input type=\"hidden\" name=\"list\" value=\"");
      out.print(elementList.getID());
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" name=\"thing\" value=\"");
      out.print(thing.getID());
      out.write("\">\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                var textBeforeChanges = \"\";\r\n");
      out.write("\r\n");
      out.write("                function onClickEdit(id) {\r\n");
      out.write("                    textBeforeChanges = document.getElementById(\"text_edit_\" + id.toString()).innerText;\r\n");
      out.write("                    var text_edit = document.getElementById(\"text_edit_\" + id.toString());\r\n");
      out.write("                    if (text_edit.contentEditable === \"false\") {\r\n");
      out.write("                        text_edit.setAttribute(\"contenteditable\", \"true\");\r\n");
      out.write("                        document.getElementById(\"button_edit_\" + id.toString()).setAttribute(\"style\", \"display: none;\");\r\n");
      out.write("                        document.getElementById(\"button_delete_\" + id.toString()).setAttribute(\"style\", \"display: none;\");\r\n");
      out.write("                        document.getElementById(\"button_yes_\" + id.toString()).setAttribute(\"style\", \"\");\r\n");
      out.write("                        document.getElementById(\"button_no_\" + id.toString()).setAttribute(\"style\", \"\");\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                function onClickYes(id) {\r\n");
      out.write("                    document.getElementById(\"thing_content_\" + id.toString()).value = document.getElementById(\"text_edit_\" + id.toString()).innerText\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                function onClickNo(id) {\r\n");
      out.write("                    document.getElementById(\"button_yes_\" + id.toString()).setAttribute(\"style\", \"display: none;\");\r\n");
      out.write("                    document.getElementById(\"button_no_\" + id.toString()).setAttribute(\"style\", \"display: none;\");\r\n");
      out.write("                    document.getElementById(\"button_edit_\" + id.toString()).setAttribute(\"style\", \"\");\r\n");
      out.write("                    document.getElementById(\"button_delete_\" + id.toString()).setAttribute(\"style\", \"\");\r\n");
      out.write("                    document.getElementById(\"text_edit_\" + id.toString()).innerText = textBeforeChanges;\r\n");
      out.write("                    document.getElementById(\"text_edit_\" + id.toString()).contentEditable = \"false\";\r\n");
      out.write("                }\r\n");
      out.write("            </script>\r\n");
      out.write("            ");

                    }
                    id++;
                }
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <hr>\r\n");
      out.write("            <h2 class=\"text-center\">Urls</h2>\r\n");
      out.write("            ");

                for (Element thing : elementList.getElementList()) {
                    if (thing.getLabel().equals("url")) {
                        String url = ((Thing) thing).getContent();
            
      out.write("\r\n");
      out.write("            <p class=\"\"><a href=\"");
      out.print(url);
      out.write('"');
      out.write('>');
      out.print(url);
      out.write("\r\n");
      out.write("            </a></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <form action=\"deleteThing.html\" method=\"POST\">\r\n");
      out.write("                <input type=\"hidden\" name=\"list\" value=\"");
      out.print(elementList.getID());
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" name=\"thing\" value=\"");
      out.print(thing.getID());
      out.write("\">\r\n");
      out.write("                <input type=\"submit\" value=\"Delete\">\r\n");
      out.write("            </form>\r\n");
      out.write("            ");

                    }
                }
            
      out.write("\r\n");
      out.write("            <hr>\r\n");
      out.write("            <h2 class=\"text-center\">Images</h2>\r\n");
      out.write("            ");

                for (Element thing : elementList.getElementList()) {
                    if (thing.getLabel().equals("image")) {
                        String image_url = ((Thing) thing).getContent();
            
      out.write("\r\n");
      out.write("            <div class=\"container text-center\">\r\n");
      out.write("                <img src=\"");
      out.print(image_url);
      out.write("\" class=\"img-fluid w-25 rounded\" alt=\"image\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <form action=\"deleteThing.html\" method=\"POST\">\r\n");
      out.write("                <input type=\"hidden\" name=\"list\" value=\"");
      out.print(elementList.getID());
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" name=\"thing\" value=\"");
      out.print(thing.getID());
      out.write("\">\r\n");
      out.write("                <input type=\"submit\" value=\"Delete\">\r\n");
      out.write("            </form>\r\n");
      out.write("            ");

                    }
                }
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"adding-section1\">\r\n");
      out.write("                <form action=\"addThing.html\" method=\"POST\">\r\n");
      out.write("                    <h2>Add new thing:</h2>\r\n");
      out.write("                    Thing content: <input type=\"text\" name=\"thing_content\" required>\r\n");
      out.write("                    <input type=\"radio\" name=\"type\" value=\"text\" checked> Text\r\n");
      out.write("                    <input type=\"radio\" name=\"type\" value=\"url\"> URL\r\n");
      out.write("                    <input type=\"radio\" name=\"type\" value=\"image\"> Image (url address)\r\n");
      out.write("                    <input type=\"hidden\" name=\"list\" value=\"");
      out.print(elementList.getID());
      out.write("\">\r\n");
      out.write("                    <input type=\"submit\" value=\"Add thing\"/>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container border shadow\">\r\n");
      out.write("            <h2 class=\"text-center\">List</h2>\r\n");
      out.write("            <div class=\"row\" style=\"font-weight: bold\">\r\n");
      out.write("                <div class=\"col-md-8 themed-grid-col \">\r\n");
      out.write("                    Element name\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 themed-grid-col\">\r\n");
      out.write("                    Element contents\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 themed-grid-col\">\r\n");
      out.write("                    Actions\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                for (Element element : elementList.getElementList()) {
                    if (element.getType().equals("list") || element.getType().equals("item")) {
                        String href = "itemListView.html?list=" + element.getID();
                        StringBuilder type = new StringBuilder();
                        if (element.getType().equals("list")) {
                            type = new StringBuilder("list (" + ((ElementList) element).getElementList().size() + " elements)");
                        } else if (element.getType().equals("item")) {
                            for (Element thing : ((ElementList) element).getElementList()) {
                                type.append(thing.getType()).append(", ");
                            }
                            if (!type.isEmpty())
                                type.delete(type.length() - 2, type.length());
                            else
                                type.append("empty item");
                        }
            
      out.write("\r\n");
      out.write("            <div class=\"row \">\r\n");
      out.write("                <div class=\"col-md-8 themed-grid-col\">\r\n");
      out.write("                    <a href=\"");
      out.print(href);
      out.write('"');
      out.write('>');
      out.print(element.getLabel());
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 themed-grid-col\">\r\n");
      out.write("                    ");
      out.print(type);
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 themed-grid-col text-center\">\r\n");
      out.write("                    <form action=\"deleteElement.html\" method=\"POST\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"item_to_delete\" value=\"");
      out.print(element.getID());
      out.write("\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"list\" value=\"");
      out.print(elementList.getID());
      out.write("\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-primary \" value=\"Delete element\">\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");

                    }
                }
            
      out.write("\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"adding-section2\">\r\n");
      out.write("                <form action=\"addElement.html\" method=\"POST\">\r\n");
      out.write("                    <h2>Add new element:</h2>\r\n");
      out.write("                    Element label: <input type=\"text\" name=\"element_label\" required>\r\n");
      out.write("                    <input type=\"radio\" name=\"type\" value=\"list\"> List\r\n");
      out.write("                    <input type=\"radio\" name=\"type\" value=\"item\" checked> Item\r\n");
      out.write("                    <input type=\"hidden\" name=\"list\" value=\"");
      out.print(elementList.getID());
      out.write("\">\r\n");
      out.write("                    <input type=\"submit\" value=\"Add element\"/>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");

        ElementList backList = (ElementList) elementList.getParent();
        String hrefBack = "#";
        if (backList.getID() == 0)
            hrefBack = "mainListView.html";
        else
            hrefBack = "itemListView.html?list=" + backList.getID();
    
      out.write("\r\n");
      out.write("    <hr>\r\n");
      out.write("    <a href=\"");
      out.print(hrefBack);
      out.write("\">\r\n");
      out.write("        Back to the previous list: ");
      out.print(backList.getLabel());
      out.write("\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
